name: Build & Upload Artifacts

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.editorconfig'

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build & Upload Windows Artifact
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller -F src/tg_group_cloner.py -n TelegramGroupCloner

      - name: Rename and make executable (Windows)
        run: |
          rename dist\\TelegramGroupCloner.exe TelegramGroupCloner-windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/TelegramGroupCloner-windows.exe
          retention-days: 1

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Get current date
        id: datetime
        run: echo "VERSION=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: Get latest commit
        id: commit
        run: |
          COMMIT=$(git log -1 --pretty=format:"%s")
          echo "MESSAGE=$COMMIT" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.datetime.outputs.VERSION }}
          name: "Release v${{ steps.datetime.outputs.VERSION }}"
          body: |
            ## TelegramGroupCloner 更新说明

            发布时间：${{ steps.datetime.outputs.VERSION }}
            发布者：${{ github.actor }}

            ### 更新内容
            ${{ steps.commit.outputs.MESSAGE }}

            ### 支持平台
            - Windows (TelegramGroupCloner-windows.exe)

            请下载对应系统的可执行文件。

          files: ./artifacts/**/*
          draft: false
          prerelease: false
